Spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_plus
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    druid:
      stat-view-servlet:
        enabled: true
        login-username: hx
        login-password: 123456
        url-pattern: /druid/*
      filter:
        stat:
          enabled: true
        wall:
          enabled:  true
        slf4j:
          enabled: true
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.jpg,*.png,*.css,/druid/*'
server:
  port: 8888
